GET http://localhost:5000/status

###

GET http://localhost:5000/stats

### Users

POST http://localhost:5000/users
Content-Type: application/json

{
	"email": "lewis33@mail.com",
	"password": "123456"
}

### Auth

GET http://localhost:5000/connect
Authorization: Basic bGV3aXNAbWFpbC5jb206MTIzNDU2

###

GET http://localhost:5000/disconnect
X-Token: 73e18052-bbb9-4d50-a008-cc6342854a48
