@url = http://localhost:5000
@token = 2639434f-efc1-4c44-9dce-ad34d23496dd

### App status

GET {{url}}/status

###

GET {{url}}/stats

### Users

POST {{url}}/users
Content-Type: application/json

{
	"email": "lewis@mail.com",
	"password": "123456"
}

###

GET {{url}}/users/me
X-Token: {{token}}

### Auth

GET {{url}}/connect
Authorization: Basic bGV3aXNAbWFpbC5jb206MTIzNDU2

###

GET {{url}}/disconnect
X-Token: {{token}}


### Files

POST {{url}}/files
X-Token: {{token}}
Content-Type: application/json

{
	"name": "myText.txt",
	"type": "file",
	"data": "SGVsbG8gV2Vic3RhY2shCg=="
}
